name: Test Linux Crawler

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install selenium pandas openpyxl
      - name: Run crawler
        run: python history_linux.py
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: weather-data
          path: 南京机场天气数据.xlsx
